package com.flashpoint.p2p.mapper.loan;

import com.flashpoint.p2p.model.loan.BidInfo;

import java.util.List;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int updateByPrimaryKey(BidInfo record);

    /**
     * 查询投资总金额
     * @return
     */
    Double selectBidAllMoney();

    /**
     * 通过商品id查询 交易记录
     * @param id
     * @return
     */
    List<BidInfo> selectBidInfoListByLoanId(Integer id);
}