package com.flashpoint.p2p.mapper.loan;

import com.flashpoint.p2p.model.loan.IncomeRecord;

import java.util.List;
import java.util.Map;

public interface IncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int updateByPrimaryKey(IncomeRecord record);

    /**
     * 分页查询收益
     * @param map
     * @return
     */
    List<IncomeRecord> selectIncomeRecordListbyPage(Map<String, Object> map);

    /**
     * 通过用户的ID查询收益记录
     * @param paramMap
     * @return
     */
    Long selectCountByUid(Map<String, Object> paramMap);

    /**
     *通过当前时间与收益状态判断对应的该收益的信息
     * @param i
     * @return
     */
    List<IncomeRecord> selectIncomeRecordByIncomeDateAndIncomeStatus(int i);
}