package com.flashpoint.p2p.mapper.user;

import com.flashpoint.p2p.model.user.FinanceAccount;
import com.flashpoint.p2p.model.user.User;

import java.util.Map;

public interface FinanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int insert(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int insertSelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    FinanceAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int updateByPrimaryKeySelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Nov 05 17:44:36 CST 2018
     */
    int updateByPrimaryKey(FinanceAccount record);

    /**
     * 根据用户id查询账户信息
     * @param user
     * @return
     */
    FinanceAccount selectFinaceAccountByUid(User user);

    /**
     * 更新用户的剩余金额
     * @param paramMap
     * @return
     */
    int updateFinanceAccountByUid(Map<String, Object> paramMap);

    /**
     * 根据充值订单号更新充值记录
     * @param paramMap
     * @return
     */
    int updateFinanceAccountByRecharge(Map<String, Object> paramMap);
}